### ISSUE TITLE
Add wkt/wkb support

### ISSUE THREAD

**Issue by sabas** [mapbox/geojson.io#232]
Could load directly a result of a postgis query via exporting in csv, example

```
SELECT osm_id,geometry FROM planet_osm_point;
```

Bluesky again :-)

**Comment by shane-axiom** [comment]
Are the devs still opposed to WKT support? I see that there [used to be opposition to supporting shapefiles](https://github.com/mapbox/geojson.io/pull/242), but I see that shapefile is now an export option in the save menu. WKT export seems like another natural export option, even if import isn't supported. And yes, Wicket is awesome, but it would be nice to have all this functionality in one place.

**Comment by tmcw** [comment]
> I see that there used to be opposition to supporting shapefiles, but shapefile is now an export option in the save menu.

Exporting Shapefiles is reasonable, importing the is not: it's at least 10x more complex to support.

Problem is as previously stated: this would require a new UI. If anyone wants to contribute that UI, go for it.

**Comment by shane-axiom** [comment]
@tmcw Just to clarify, I'm not asking for shapefile import. I'm asking for WKT export.

**Comment by tmcw** [comment]
Yes, just to be clear about my reasoning on the other issue, which was a rejected PR for shapefile importing, and I eventually implemented exporting. Which is to say: i'm more liberal with adding export formats than import formats, because you can safely export one kind of thing, but in importing you need to handle all variants.
