### ISSUE TITLE
"login" link requests access to private Git repositories

### ISSUE THREAD

**Issue by kerrick-lyft** [mapbox/geojson.io#506]
When I click the "login" link in the upper right corner of the page, it asks me to share all my private GitHub repositories. I don't think this should be required to login (and I definitely don't want to share my private repositories :) ).
![screen shot 2016-04-22 at 4 03 59 pm](https://cloud.githubusercontent.com/assets/15618653/14756991/0c8d8ea2-08a4-11e6-9dd0-136e4cc5210a.png)

**Comment by tmcw** [comment]
* https://github.com/mapbox/geojson.io/issues/318
* https://github.com/mapbox/geojson.io/issues/332
* https://github.com/mapbox/geojson.io/issues/384

To quote from the last:

---

So, I started with wide permissions, then someone requested they be narrowed down since they were security-wary, and then that cropped up as a perceived bug when people didn't see their private repos, so I made them wide again.

So, since accessing private repos is a vital feature for some and a deal-breaking security concern for others, making you feel better would make other people feel worse and vice versa. Unless someone does the legwork to have it both ways (which is possible, I'd guess), I'm going to leave this switch in the 'more useful' position rather than the 'more paranoid one', since this is, after all, an open source project with zero server component that's very simple to audit.
