### ISSUE TITLE
Scale and Drawn Marker VIsibility

### ISSUE THREAD

**Issue by remmi11** [mapbox/geojson.io#524]
Not an issue and this may not be in the realm of support here. 
How can I set a minZoom on items in layer group created by the draw toolbar.
The icons become very crowded when visible at full extent.  Where might this adjustment take place?

**Comment by tmcw** [comment]
Hi @remmi11,

Sure, this is outside the scope of geojson.io - because geojson.io is focused on editing data, and not especially on its presentation besides showing it for editing.

Most likely, [marker clustering with the Leaflet.MarkerCluster plugin](https://github.com/Leaflet/Leaflet.markercluster) will get you what you want: it automatically consolidates nearby features into clusters.

- Tom
