### ISSUE TITLE
mapbox-gl-js integration

### ISSUE THREAD

**Issue by pratheekrebala** [mapbox/geojson.io#528]
Hey Tom,

I was wondering if GL-JS integration is on the roadmap for the tool? We are implementing geojson.io for a project using Mapbox-GL-JS for rendering the map on client side and it would be awesome to use the Geojson interface to edit properties like marker size, color etc. and use them in a GL-JS client.

If there's interest, I'd like to take a crack at implementing mapbox-gl on geojson.io as a configuration flag that would use GL-JS to render instead of mapbox.js.

Thanks,
Pratheek

**Comment by tmcw** [comment]
Pratheek,

Sure! The preferred route is to download the GeoJSON and host it elsewhere - geojson.io as a display mechanism is secondary to its purpose for editing data. Additionally, GL JS doesn't have a style-in-data mechanism like our GeoJSON support does (simplestyle-spec) and there aren't really plans to support simplestyle-spec, because it leans heavily toward convenience over control.

But I'm sure other folks are also interested in getting geojson.io on the GL JS train, and if you're interested in trying it out, I'm open to most sorts of contributions!

- Tom

**Comment by tmcw** [comment]
Closing; happy to see a PR.

**Comment by pratheekrebala** [comment]
Hi @tmcw - apologies about the lack of activity on this. I will send a PR this week. Thanks.
