### ISSUE TITLE
Page crashes when trying to open topo/geojson

### ISSUE THREAD

**Issue by electro3006** [mapbox/geojson.io#536]
I have a geo/topojson file with 18000 polygons, and it is 12Mb large. 
I can open the file using mapshaper, arcgis and qgis, but geojson.io always crashes.
Any help is appreciated.

Thanks!

**Comment by tmcw** [comment]
Hello!

Unfortunately this isn't likely to work: geojson.io is a client-side application, limited by the performance of JavaScript and all of its component libraries. Most GeoJSON data is relatively small - smaller than 12mb/18k features, and it works very well for those datasets, but larger datasets are expected to crash. Since this varies with different computers, we don't have a hard limit for how much data it can handle, but this dataset is certainly hitting the limit.

- Tom

**Comment by electro3006** [comment]
Hi Tom,

Thank You for the assistance. I'll try to break up the file into few geojson files, and see what happens.
Thanks again!

Djordje
