### ISSUE TITLE
Draw a circle

### ISSUE THREAD

**Issue by AgustinQuetto** [mapbox/geojson.io#537]
Hi. I changed the false to true value in the circle and draw and drop a point is created. Any solution? Thanks.

**Comment by tmcw** [comment]
Yep, Leaflet.draw adds a [L.Circle](http://leafletjs.com/reference-1.0.0.html#circle) to the map. GeoJSON, the standard, doesn't have a built-in circle type, so it has no representation for L.Circle, except as a many-vertexed-polygon, which is unlikely to be what people want (and L.Circle is already a little misleading). Happy to accept a PR that implements Circle drawing, but the Leaflet Draw behavior is not currently usable because it does not work with GeoJSON.

**Comment by tomscholz** [comment]
I will give it a shot :) @tmcw

**Comment by ingalls** [comment]
Closing as stale
