### ISSUE TITLE
Add arrow marker type for the a feature and support heading property.

### ISSUE THREAD

**Issue by gardster** [mapbox/geojson.io#540]
It will be awesome, if I can visualize heading (bearing) property in geojson.io

**Comment by tmcw** [comment]
Thanks for the suggestion! geojson.io is primarily a tool for editing GeoJSON that tries to add little if any interpretation of the data. In custom code, ou can really go all-out with how GeoJSON properties affect styles, but in GeoJSON, we don't want to promise too much about how properties affect the style - since that'd allow people to conclude that adding a `bearing` property to a GeoJSON point will add a bearing icon in _any_ renderer of that GeoJSON, not just in geojson.io. And, similarly, we may have some users who use `bearing` as an arbitrary property, not a direction, and would be surprised by this addition.

So, though it's a cool idea, I'm going to close this issue since it doesn't quite fit into the purpose of geojson.io. If you've got some requirement to map bearings, you're more than welcome to fork or adapt the code to your desires!

- Tom
