### ISSUE TITLE
add google maps?

### ISSUE THREAD

**Issue by prashantwosti** [mapbox/geojson.io#558]
Is it possible to integrate google maps too? I'm not a web developer but i really need to map paths and points over google maps.

**Comment by tmcw** [comment]
Sorry, can't. Tracing Google Maps is against their terms of service.

**Comment by prashantwosti** [comment]
Thanks @tmcw. But I can still make it on my own right?

**Comment by wboykinm** [comment]
@prashantwosti We'd really discourage you from tracing on Google's basemap at all. Any derivation, individual or otherwise, is a violation of their terms ([section 10.5b](https://developers.google.com/maps/terms#10-license-restrictions)). But within Google's ecosystem, you can use the tools they've built for map annotation. I'd suggest you try their [My Maps](https://www.google.com/mymaps) app.
