### ISSUE TITLE
Super slow UI

### ISSUE THREAD

**Issue by kozyr** [mapbox/geojson.io#584]
UI simply freezes after pasting and deleting bunch of GeoJSON. Anything bigger than 100 or so coordinates shuts this down.

**Comment by ingalls** [comment]
@kozyr This is typically due to having to parse our and represent each of the points. If you are rendering large amounts of GeoJSON in the browser I would recommend either uploading them to mapbox.com and styling with the dataset editor or vectorizing them yourself via: https://github.com/mapbox/tippecanoe

Eventually we plan to switch GeoJSON.io over to using vector tiles internally which should significantly improve the sites handling of larger GeoJSON files.
