### ISSUE TITLE
Mention limits: 200 features max, 130 points, etc.

### ISSUE THREAD

**Issue by jidanni** [mapbox/geojson.io#600]
We see
```
I've got data
If you have data, like a KML, GeoJSON, or CSV file, just drag & drop it onto the page or click 'Open' and 'File' - your data should appear on the map!
```
but shouldn't you mention some limits?
1. Welcome to add GeoJSON data up to 200 features. Any more and you must be a Gold Member.
2. Welcome to add GeoJSON data. Note that after 100 points the program is not guaranteed to work anymore.
3. Welcome to add GeoJSON data. We have tested adding 8000 point features with no problem. Else if you run into a problem submit a bug report.

**Comment by tmcw** [comment]
There are no hard limits of geojson.io: bigger computer, bigger datasets. A faster browser gets released, larger datasets are supported. And even under those limits, trying to quantify complexity is a losing battle: you can say "up to 100 features are supported", but if each feature has a million vertices, then it won't be. I'd recommend this issue be closed, because, well, there's no real action here.

**Comment by jidanni** [comment]
OK then explicitly say there are no limits. Thanks.
Other such software mention limits, so one thinks there must be some.
