### ISSUE TITLE
can the draw Polygon be imported?

### ISSUE THREAD

**Issue by JarlRyan** [mapbox/geojson.io#614]
can the draw Polygon be imported,like svg..

**Comment by bhousel** [comment]
Hey @JarlRyan - a GeoJSON polygon can't be imported from SVG because SVG polygons are in "screen" coordinates (x,y), and GeoJSON polygons are assumed to be in ESPG:4326 (longitude, latitude). 

Reprojecting SVG to EPSG:4326 for use in geojson.io would depend on the zoom level and latitude where you want the shape to appear.  You could use a conversion library like [proj4](http://proj4.org/) or [d3.geo](https://medium.com/@mbostock/command-line-cartography-part-1-897aa8f8ca2c) to do this, but it's not automatic - expect do to a lot of work to get your shape converted.
