### ISSUE TITLE
Projection type of the coordinates?

### ISSUE THREAD

**Issue by MichaelMuinos** [mapbox/geojson.io#640]
I apologize if this is an easily known question, but I am attempting to display the geojson that was generated using geojson.io; however, I am unsure of the projection being used. For example, this is what I have generated.

`{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "name": "North America"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -531.650390625,
              63.82128765261384
            ],
            [
              -532.2216796875,
              63.39152174400882
            ],
            [
              -530.9912109374999,
              63.3324127919358
            ],
            [
              -529.8046875,
              62.85514553774182
            ],
            [
              -528.4423828125,
              63.25341156651705
            ],
            [
              -530.068359375,
              63.78248603116502
            ],
            [
              -531.03515625,
              63.64625919492172
            ],
            [
              -531.650390625,
              63.82128765261384
            ]
          ]
        ]
      }
    }
  ]
}`

Am I doing something wrong for it to be generated in this format?

**Comment by sgillies** [comment]
@MichaelMuinos looks like these features were traced from a wrapped view of the world. It's possible to do this with geojson.io and it's not sophiscated enough to unwrap. The GeoJSON should be OGC CRS84 (roughly EPSG:4326). If you add 360 to the longitudes you may get data you can use in other applications. Or, you could have the data re-generated so that all longitude values are between -180 and 180.
